version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: timeedge-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    container_name: timeedge-app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo-data:
